### PR TITLE
You gotta have npm installed right?

### PR DESCRIPTION
**Pull request by eye-sigil**

### CODE REVIEW

**Comment by Ratismal** [comment]
NPM comes with node.js though, can you give a situation in which you *wouldn't* have NPM installed?

**Comment by eye-sigil** [comment]
Not a javascript developer?

**Comment by Ratismal** [comment]
But I specifically state that you require node.js. NPM comes with node.js. Why would you have node.js installed but not NPM?

**Comment by charlesmilette** [comment]
In that case I think we can `s/npm/nodejs/`

If you don't have node installed and don't know what it is you'll have a hard time figuring it out.

**Comment by Ratismal** [comment]
I'm going to close this because node.js includes npm with installation, and node.js is marked as a requirement. I *will*, however, move the requirement section farther up so that it's more noticeable.

If you can provide a convincing use case wherein a user would have node.js installed without npm, this can be reopened.

**Pull request closed without merging**
