### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by Chewsterchew**
im the typo kitty here to fix

### CODE REVIEW

**Comment by Ratismal** [comment]
have fun with your unsquashed merge :^)

**Comment by Chewsterchew** [comment]
i really hate discord

**Comment by Chewsterchew** [comment]
like imagine being so low you just be an asshole pretending to be all clever and shit

**Comment by Chewsterchew** [comment]
image
what a threat
the client doesnt even work anyway

**Comment by kot83** [comment]
b a d m e m e

**Comment by Chewsterchew** [comment]
aaaaa

**Comment by cking** [comment]
a) this client works reportedly wonderfully on several computers
b) this is for issues, to for discussions and smalltalk use discord

**Comment by Chewsterchew** [comment]
ok sorry

**Pull request merged**
