### PR TITLE
Fix discord mutator

### PR DESCRIPTION
**Pull request by Snazzah**

### CODE REVIEW

**Comment by rauenzi** [comment]
For the interim you can do something similar to `let reactProps = instance.memoizedProps || instance._currentElement` then access the needed vars like `reactProps.children.props.unread` since it will work for both canary and stable.

**Comment by Ratismal** [comment]
My concern with this is backwards compatibility. Does this work in stable?

**Comment by rauenzi** [comment]
The changes in the PR are not, but if they use what I suggested it will work for both.

**Comment by cking** [comment]
Already solved I guess ;)

**Pull request closed without merging**
